quotes/quotes/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes_list.urls')),
    path('', include('users.urls')),
    path('', include('scraping.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/quotes_list/urls.py
from django.urls import path
from . import views

app_name = 'quotes_list'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/<int:author_id>', views.author, name='author'),
    path('authors', views.authors, name='authors'),
    path('add/tag', views.addtag, name='addtag'),
    path('add/author', views.addauthor, name='addauthor'),
    path('add/quote', views.addquote, name='addquote'),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('signin/', views.signinuser, name='signin'),
    path('logout/', views.logoutuser, name='logout'),
    path('users/reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('users/reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('users/reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('users/reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(max_length=50, required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(max_length=50, required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm


# Create your views here.
def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes_list:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(to='users:signin')
        else:
            print(form.errors)
            return render(request, 'users/signup.html', context={'form': form})

    return render(request, 'users/signup.html', context={'form': RegisterForm()})


def signinuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes_list:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])

        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users/signin')

        login(request, user)
        return redirect(to='quotes_list:main')

    return render(request, 'users/signin.html', context={'form': LoginForm})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes_list:main')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

quotes/users/templates/users/base-sign-forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes_list/style.css' %}">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5 mb-5">
            <h1 class="mb-4 text-center"><a href="{% url 'quotes_list:main' %}">Quotes List</a></h1>

            {% block form %}{% endblock %}

        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

quotes/users/templates/users/password_reset.html
{% extends 'users/base-sign-forms.html' %}

{% block form %}
<div class="card">
    <div class="card-header">
        <h2 class="h3 m-0 font-weight-normal">Reset Password</h2>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"  class="btn btn-primary btn-block">Request password reset</button>
        </form>
    </div>
    <div class="card-footer">
        <p class="m-0">If you don\'t have profile, please <a href="{% url 'users:signup' %}">sign up</a></p>
    </div>
</div>
{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "users/base-sign-forms.html" %}

{% block form %}

    <h2>Password reset complete!</h2>
    <p><a href="{% url 'users:signin' %}">sign up</a></p>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "users/base-sign-forms.html" %}

{% block form %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "users/base-sign-forms.html" %}

{% block form %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes/users/templates/users/signin.html
{% extends 'users/base-sign-forms.html' %}

{% block form %}
<div class="card">
    <div class="card-header">
        <h2 class="h3 m-0 font-weight-normal">Please sign in</h2>
    </div>
    <div class="card-body">
        {% if messages %}
        <div>
            {% for message in messages %}
            <div {% if message.tags %} class="alert-{{ message.tags}} text-danger" {% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}

        <form method="post" action="{% url 'users:signin' %}">
            {% csrf_token %}
            <div class="form-group">
                <label>Username:</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label>Password:</label>
                {{ form.password }}
            </div>
            <button class="btn btn-primary btn-block" type="submit">Sign in</button>
            <p class="mb-0 mt-3"><a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a></p>
        </form>
    </div>
    <div class="card-footer">
        <p class="m-0">If you don't have profile, please <a href="{% url 'users:signup' %}">sign up</a></p>
    </div>
</div>
{% endblock %}

quotes/users/templates/users/signup.html
{% extends 'users/base-sign-forms.html' %}

{% block form %}
<div class="card">
    <div class="card-header">
        <h2 class="h3 m-0 font-weight-normal">Please sign up</h2>
    </div>
    <div class="card-body">
        <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            <div class="form-group">
                <label>Username:</label>
                {{ form.username }}
                <span class="form-text text-danger">{{ form.errors.username.as_text }}</span>
            </div>
            <div class="form-group">
                <label>Email:</label>
                {{ form.email }}
                <span class="form-text text-danger">{{ form.errors.email.as_text }}</span>
            </div>
            <div class="form-group">
                <label>Password:</label>
                {{ form.password1 }}
                <span class="form-text text-danger">{{ form.errors.password1.as_text }}</span>
            </div>
            <div class="form-group">
                <label>Password confirmation:</label>
                {{ form.password2 }}
                <span class="form-text text-danger">{{ form.errors.password2.as_text }}</span>
            </div>
            <button class="btn btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </div>
    <div class="card-footer">
        <p class="m-0">If you already have profile, please <a href="{% url 'users:signin' %}">sign up</a></p>
    </div>
</div>
{% endblock %}