quotes/quotes/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes_list.urls')),
    path('', include('users.urls')),
    path('', include('scraping.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/scraping/urls.py
from django.urls import path
from . import views

app_name = 'scraping'

urlpatterns = [
    path('scraping', views.main, name='scraping'),
    path('uploadauthors', views.uploadauthors, name='uploadauthors'),
    path('uploadquotes', views.auploadquotes, name='uploadquotes'),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('signin/', views.signinuser, name='signin'),
    path('logout/', views.logoutuser, name='logout'),
    path('users/reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('users/reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('users/reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('users/reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/scraping/models.py
from django.db import models

# Create your models here.

quotes/scraping/views.py
from django.shortcuts import render, redirect
import json
from quotes_list.models import Author, Tag, Quote
from datetime import datetime

def main(request):
    return render(request, 'scraping/index.html')


def uploadauthors(request):
    if request.method == 'POST' and request.FILES['json_file']:
        json_file = request.FILES['json_file']
        data = json.load(json_file)

        for item in data:
            author = Author.objects.create(
                fullname=item['fullname'],
                born_date=datetime.strptime(item['born_date'], "%B %d, %Y"),
                born_location=item['born_location'],
                description=item.get('description', '')
            )

        return redirect(to='quotes_list:authors')

    return render(request, 'scraping/index.html')

def auploadquotes(request):
    if request.method == 'POST' and request.FILES['json_file']:
        json_file = request.FILES['json_file']
        data = json.load(json_file)

        for item in data:
            # Получение id автора по fullname
            author_id = Author.objects.get(fullname=item['author']).id

            # Создание или получение тегов
            tags = [Tag.objects.get_or_create(name=tag)[0] for tag in item['tags']]

            # Создание цитаты
            quote = Quote.objects.create(
                author_id=author_id,
                quote=item['quote']
            )

            # Добавление тегов к цитате
            quote.tags.set(tags)

        return redirect(to='quotes_list:main')

    return render(request, 'scraping/index.html')

quotes/scraping/templates/scraping/index.html
{% extends 'quotes_list/base.html' %}

{% block content %}
<h1>Upload data</h1>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title m-0">Authors</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{% url 'scraping:uploadauthors' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="custom-file mb-3">
                                <input type="file" name="json_file" class="custom-file-input" id="customFile" accept="json" required>
                                <label class="custom-file-label" for="customFile">Choose file</label>
                                <small class="form-text text-muted">
                                    Select JSON file
                                </small>
                            </div>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <div class="card-title">Example:</div>
                        <code><pre>
[
    {
        "fullname": "Author Name",
        "born_date": "March 14, 1879",
        "born_location": "in Ulm, Germany",
        "description": "About author",
    }
]
                        </pre>  </code>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title m-0">Quotes</h5>
            </div>
            <div class="card-body">
                <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{% url 'scraping:uploadquotes' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="custom-file mb-3">
                                <input type="file" name="json_file" class="custom-file-input" id="customFile" required>
                                <label class="custom-file-label" for="customFile">Choose file</label>
                                <small class="form-text text-muted">
                                    Select JSON file
                                </small>
                            </div>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <div class="card-title">Example:</div>
                        <code><pre>
[
    {
        "tags": ["change", "deep-thoughts", "thinking", "world"],
        "author": "Albert Einstein",
        "quote": "\u201cThe world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.\u201d"},
    }
]
                        </pre>  </code>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}