quotes/quotes/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes_list.urls')),
    path('', include('users.urls')),
    path('', include('scraping.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/quotes_list/urls.py
from django.urls import path
from . import views

app_name = 'quotes_list'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/<int:author_id>', views.author, name='author'),
    path('authors', views.authors, name='authors'),
    path('add/tag', views.addtag, name='addtag'),
    path('add/author', views.addauthor, name='addauthor'),
    path('add/quote', views.addquote, name='addquote'),
]

quotes/scraping/urls.py
from django.urls import path
from . import views

app_name = 'scraping'

urlpatterns = [
    path('scraping', views.main, name='scraping'),
    path('uploadauthors', views.uploadauthors, name='uploadauthors'),
    path('uploadquotes', views.auploadquotes, name='uploadquotes'),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('signin/', views.signinuser, name='signin'),
    path('logout/', views.logoutuser, name='logout'),
    path('users/reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('users/reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('users/reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('users/reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quotes_list/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=255, null=False, unique=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}'


class Author(models.Model):
    fullname = models.CharField(max_length=255, null=False, unique=True)
    born_date = models.DateField(null=True)
    born_location = models.CharField(max_length=255, null=False)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.fullname}'


class Quote(models.Model):
    tags = models.ManyToManyField(Tag, related_name="tags")
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField(null=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quote}'

quotes/quotes_list/forms.py
from django import forms
from .models import Tag, Quote, Author


class AddTag(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': 'true'}))

    class Meta:
        model = Tag
        fields = ['name']


class AddAuthor(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': 'true'}))
    born_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
    born_location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class AddQuote(forms.ModelForm):
    quote = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.all()
        self.fields['author'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags']

quotes/quotes_list/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Quote, Author, Tag
from .forms import AddTag, AddAuthor, AddQuote


# Create your views here.
def main(request):
    tags_with_usage = Tag.objects.annotate(num_quotes=Count('tags'))
    sorted_tags = tags_with_usage.order_by('-num_quotes')
    tags = sorted_tags[:10]

    tag_name = request.GET.get('tag')

    if tag_name:
        quotes = Quote.objects.filter(tags__name=tag_name).order_by('-created')
    else:
        quotes = Quote.objects.all().order_by('-created')

    items_per_page = 10
    paginator = Paginator(quotes, items_per_page)

    page = request.GET.get('page')

    try:
        quotes_page = paginator.page(page)
    except PageNotAnInteger:
        quotes_page = paginator.page(1)
    except EmptyPage:
        quotes_page = paginator.page(paginator.num_pages)

    page_range = range(1, quotes_page.paginator.num_pages + 1)

    return render(request, 'quotes_list/index.html',
                  context={"quotes": quotes_page, 'page_range': page_range, 'tags': tags})


def authors(request):
    authors = Author.objects.all().order_by('fullname')
    return render(request, 'quotes_list/authors.html', {"authors": authors})


def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotes_list/author.html', {"author": author})


@login_required
def addtag(request):
    tags = Tag.objects.all().order_by('-created')[:30]

    if request.method == 'POST':
        form = AddTag(request.POST)

        if form.is_valid():
            form.save()
            return redirect(to='quotes_list:addtag')
        else:
            return render(request, 'quotes_list/add/tag.html', {"form": form, 'tags': tags})

    return render(request, 'quotes_list/add/tag.html', context={'form': AddTag, 'tags': tags})


@login_required
def addauthor(request):
    if request.method == 'POST':
        form = AddAuthor(request.POST)

        if form.is_valid():
            instance = form.save()
            return redirect('quotes_list:author', author_id=instance.pk)
        else:
            return render(request, 'quotes_list/add/author.html', {"form": form})

    return render(request, 'quotes_list/add/author.html', context={'form': AddAuthor})


@login_required
def addquote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = AddQuote(request.POST)

        if form.is_valid():
            new_quote = form.save()

            choise_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))

            for tag in choise_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quotes_list:main')
        else:
            return render(request, 'quotes_list/add/quote.html', {"form": form, 'tags': tags})

    return render(request, 'quotes_list/add/quote.html', context={'form': AddQuote, 'tags': tags})

quotes/quotes_list/templates/quotes_list/author.html
{% extends 'quotes_list/base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h2 class="card-title m-0">{{ author.fullname }}</h2>
    </div>
    <div class="card-body">
        <p><b>Born:</b> {{ author.born_date }} in {{ author.born_location }}</p>
        <p><b>Description:</b></p>
        <p>{{ author.description }}</p>
    </div>
</div>
{% endblock %}

quotes/quotes_list/templates/quotes_list/authors.html
{% extends 'quotes_list/base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title m-0">Authors</h3>
    </div>
    <div class="card-body">
        <ul class="list-unstyled">
        {% for author in authors %}
        <li><a href="{% url 'quotes_list:author' author.id %}">{{ author.fullname }}</a></li>
        {% endfor %}
        </ul>

    </div>

</div>
{% endblock %}

quotes/quotes_list/templates/quotes_list/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Quotes</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes_list/style.css' %}">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-primary justify-content-between box-shadow">
    <a href="/" class="navbar-brand">Quotes List</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'quotes_list:authors' %}">Authors</span></a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'quotes_list:addquote' %}">New Quote</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'quotes_list:addauthor' %}">New Author</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'quotes_list:addtag' %}">New Tag</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'scraping:scraping' %}">Upload from JSON</span></a>
        </li>
        {% endif %}
    </ul>
    {% if user.is_authenticated %}
    <span class="navbar-text text-white">
    Welcome <b>
        {% if user.is_staff %}
        <a href="/admin/">{{ user.username }}</a>
        {% else %}
        {{ user.username }}
        {% endif %}
    </b>!
    </span>
    <a href="/logout/" class="nav-link navbar-brand">Logout</a>
    {% else %}
    <a href="/signin/" class="nav-link navbar-brand">Login</a>
    {% endif %}
</nav>

<main role="main" class="container">

    <div class="row">
        <div class="col-md-9">

            {% block content %}{% endblock %}

        </div>
        <div class="col-md-3">

            {% block sidebar %}{% endblock %}

        </div>
    </div>

</main><!-- /.container -->
<footer class="footer">
    <div class="container">
        <span class="text-muted">Quotes by <a href="http://quotes.toscrape.com/">Quotes  to Scrape</a></span>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

quotes/quotes_list/templates/quotes_list/index.html
{% extends 'quotes_list/base.html' %}
{% load extract_tags %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title m-0">Quotes</h3>
    </div>
    <div class="card-body">
        {% for quote in quotes %}
        <blockquote class="blockquote mb-0">
            <p>{{ quote.quote}}</p>
            <footer class="blockquote-footer">
                <a href="{% url 'quotes_list:author' quote.author.id %}">{{ quote.author.fullname }}</a>
            </footer>
            <div class="mt-2"><small>Tags:</small>
                {% for tag in quote.tags|tags %}
                <a href="?tag={{ tag.name }}" class='badge badge-primary'>{{ tag.name }}</a>
                {% endfor %}
            </div>
        </blockquote>
        {% endfor %}
    </div>
    {% if quotes.paginator.num_pages > 1 %}
    <div class="card-footer">
        <nav aria-label="Page navigation example">
            <ul class="pagination m-0">
                {% if quotes.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ quotes.previous_page_number }}">Previous</a></li>
                {% endif %}
                {% for number in page_range %}
                    {% if number != quotes.number %}
                    <li class="page-item"><a class="page-link" href="?page={{ number }}">{{ number }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link">{{ number }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if quotes.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ quotes.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title m-0">
            Top 10 tags
        </h3>
    </div>
    <div class="card-body">
        <ul class="list-unstyled top-tags">
            {% for tag in tags %}
            <li><a href="?tag={{ tag.name }}" class="badge badge-primary">{{ tag.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}